### ISSUE TITLE
SupeGlue blank page and not allowing to search on WEB UI

### ISSUE THREAD

**Issue by akumarb2010** [intuit/superglue#10]
<img width="1579" alt="SuperGlue_blank_page_issue" src="https://user-images.githubusercontent.com/1168266/68145279-4f6f3000-feea-11e9-9c07-48445a2881ef.png">
**Describe the bug**
after parsing and Elastic search load, it’s showing a blank page and not allowing to search anything on WEB UI.

**To Reproduce**
You can reproduce it by following README.

**Expected behavior**
NA

**Screenshots**
Adding the screenshot

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser [chrome]

[](url)

**Comment by nicholastmosher** [comment]
Ah, this is somewhat of a known issue that we never wrote down anywhere. All that's happening is that the UI is scaled up too large by default. If you zoom out of your webpage using Ctrl-minus (or Cmd-minus) you should be able to see the search bar. It's still something that should be fixed, but if you want to try using the webapp immediately that's a quick workaround.

**Comment by akumarb2010** [comment]
@nicholastmosher  Thanks for the quick response Nick. 

Yes, I am able to search after zooming in, but for community awareness purpose raised this issue until it is fixed.
