### ISSUE TITLE
Lineage API depth -1 throws 500 error

### ISSUE THREAD

**Issue by sambekar15** [intuit/superglue#18]
**Describe the bug**
Lineage API depth -1 throws 500 error. Negative depth is not supported . Instead of throwing exception it should gracefully handle the error 

**To Reproduce**
GET call on lineage api - http://localhost:8080/api/v1/lineage/table/LOREM?bw=-1&fw=-1
Unexpected error constructing lineage for table "LOREM"

![image](https://user-images.githubusercontent.com/37278275/94317452-3a085780-ff3b-11ea-9538-caf0244cf0b3.png)

**Expected behavior**
Should return Validation Error (404)  status code with formatted json Response

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by amitnagesh** [comment]
@sambekar15  can I take this one?

**Comment by sambekar15** [comment]
> @sambekar15 can I take this one?

Sure . Assigned to you.
