### ISSUE TITLE
Lineage API depth 0 throws Not Found error

### ISSUE THREAD

**Issue by sambekar15** [intuit/superglue#20]
**Describe the Issue**
 If you specify  bw=0, fw=0 it returns Table Not found.
 
The table actually exists but it does not have any edges. 

**To Reproduce**
http://localhost:8080/api/v1/lineage/table/LOREM?bw=0&fw=0
![image](https://user-images.githubusercontent.com/37278275/94322491-9d988200-ff47-11ea-976d-fe0e1909cfcc.png)

**Expected behavior**
Return only one table node

**Comment by srikalam** [comment]
@sambekar15 I would like to this up for the OSD.

**Comment by sambekar15** [comment]
> @sambekar15 I would like to this up for the OSD.

Sure join this slack channel - #opentrack-superglue
