### ISSUE TITLE
Enable traversal of graph on UI by depth

### ISSUE THREAD

**Issue by sambekar15** [intuit/superglue#21]
Currently the Superglue UI only allows us to see the lineage of depth 1. However, the backend API has capabilities for different depths (1 through 4, -1 for full lineage), so we want to augment the UI to display those lineages to the user.

**Describe the solution you'd like**
We want to have a drop down that will let you choose the depth, and make a call to the backend with the new depth. Then the UI can display the new lineage with the new depth once the fetching is complete.

**Describe alternatives you've considered**
We are open to other approaches in displaying different depths on the UI.

**Additional context**

**Comment by bv777** [comment]
Hello, I am interested in this issue and the Superglue project as a whole. I have had an issue with setting up the development environment. Once I finished loading the example data with `superglue elastic --load`, I went to `http://localhost:8080` and saw the following screen:

![Screen Shot 2020-10-16 at 1 41 39 PM](https://user-images.githubusercontent.com/17304826/96290895-538a4580-0fb5-11eb-8213-23477b252b88.png)

I have attached the docker logs:
[superglue_docker.log](https://github.com/intuit/superglue/files/5393392/superglue_docker.log)
that have this error:
```
nginx       | 172.20.0.1 - - [16/Oct/2020:17:34:46 +0000] "GET / HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
nginx       | 2020/10/16 17:34:46 [error] 6#6: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.20.0.3:3000/", host: "localhost:8080"
```

**Comment by soojison** [comment]
> Hello, I am interested in this issue and the Superglue project as a whole. I have had an issue with setting up the development environment. Once I finished loading the example data with `superglue elastic --load`, I went to `http://localhost:8080` and saw the following screen:
> 
> ![Screen Shot 2020-10-16 at 1 41 39 PM](https://user-images.githubusercontent.com/17304826/96290895-538a4580-0fb5-11eb-8213-23477b252b88.png)
> 
> I have attached the docker logs:
> [superglue_docker.log](https://github.com/intuit/superglue/files/5393392/superglue_docker.log)
> that have this error:
> 
> ```
> nginx       | 172.20.0.1 - - [16/Oct/2020:17:34:46 +0000] "GET / HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
> nginx       | 2020/10/16 17:34:46 [error] 6#6: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.20.0.3:3000/", host: "localhost:8080"
> ```

This is a very old issue, but I am commenting for those who are encountering the same issue. Try increasing the RAM of the docker container to more than 2G, and restart all the services. Then try the steps from `superglue parse` and then on.

**Comment by BennettElisa** [comment]
I'm interested in working on this issue but would like to better understand what language the graph traversal should be coded in.
