### ISSUE TITLE
Local set up throws 502 error with the url http://localhost:8080

### ISSUE THREAD

**Issue by srikalam** [intuit/superglue#27]
Followed all the set up steps per Readme and get 502 error with http://localhost:8080. The error log is below

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Did the following setup steps:
docker-compose -f deployments/development/docker-compose.yml up
./gradlew installDist
export PATH="${HOME}/.superglue/bin:${PATH}"
cd examples
superglue init --database
# In examples/
superglue parse
superglue elastic --load

2. The configuration is same as default in the git
3. Send a request like  http://localhost:8080
4. Error:
nginx       | 172.20.0.1 - - [01/Oct/2020:21:31:55 +0000] "GET /app HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
nginx       | 172.20.0.1 - - [01/Oct/2020:21:31:56 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
nginx       | 172.20.0.1 - - [01/Oct/2020:21:31:58 +0000] "GET / HTTP/1.1" 502 158 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
nginx       | 2020/10/01 21:31:58 [error] 7#7: *51 connect() failed (113: No route to host) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.20.0.4:3000/", host: "localhost:8080"

**Expected behavior**
Should display the UI

**Screenshots**

**Desktop (please complete the following information):**
 - OS:   MacOS Catalina 10.15.4
 - Browser - both Chrome and Safari
 - Version
java -version
openjdk version "11.0.7" 2020-04-14 LTS

Docker:
docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by soojison** [comment]
Hey Srikala, the UI needs to compile and first before it can be accessed. My guess was it was not completely loaded before you accessed the address. 

Were you able see this output in the logs?
<img width="1829" alt="Screen Shot 2020-10-01 at 4 58 26 PM" src="https://user-images.githubusercontent.com/10430283/94867777-7d653900-0407-11eb-98c7-673708ee0dc4.png">

**Comment by srikalam** [comment]
yes, I didn't see the above output in my logs even after few hours. Looks the UI build didn't get triggered
![image](https://user-images.githubusercontent.com/6180774/94868793-b77b0e80-03f8-11eb-89c7-98d90e37561f.png)

**Comment by lingyv-li** [comment]
I think this is due to Intuit internal npm registry is used in yarn.lock. I can create a PR to fix it.
